#pragma once

enum class SceneTag : int {
    MAIN_MENU_SCENE = 0,
    GAME_SCENE,
    SHIP_SCENE,
    AREA_SCENE,
    ROOM1_SCENE,
    ROOM2_SCENE,
    ROOM3_SCENE,
    ROOM4_SCENE,
    ROOM5_SCENE,
    ROOM6_SCENE,
    ROOM7_SCENE,
    ROOM8_SCENE,
    ROOM9_SCENE,
    LAPTOP_SCENE,
    EVALUATION_SCENE
};
